### ISSUE TITLE
Application crash on initialization, when updating Facebook SDK

### ISSUE THREAD

**Issue by filbabic** [talkable/android-sdk#12]
When updating the version of the Facebook Android SDK (`com.facebook.android:facebook-android-sdk`), Talkable causes the app to crash on every runtime, due to a wrong function accessor.

We currently use the `v14.1.1` FB SDK on Android which is pretty old. It's using the v14 Graph API. The latest version of the SDK is 17.0.1, which I assume uses v20 or something close to the latest version. (of the Graph API).

The constraints for the GraphAPI are that it has to be updated to v15 minimum soon, since v14 is reaching its 2-year-lifetime.

Unfortunately, we’re unable to upgrade anywhere above 15.1.0 because the Facebook SDK has breaking changes internally to one of its API (`MessengerUtils.isMessengerInstalled()`), making it non-static vs static and changing its accessor. Now, usually we’d be able to just make the changes ourselves to the new API, Talkable uses this API under the hood and running the app crashes because of this compiled code issue. (accessing a non-static/virtual method in a static way/context)

Looking through the codebase of the `MessengerUtils`, the function is still a part of the object and is technically static in Kotlin, but it no longer has `@JvmStatic` annotation.

A fix could be to do something like:

```kotlin
FacebookSignatureValidator.validateSignature(context, MessengerUtils.PACKAGE_NAME);
```

Since this is what's called under the hood and `FacebookSignatureValidator.validateSignature` is annotated correctly with static context and the `MessengerUtils.PACKAGE_NAME` is also publically available.

**Comment by dgtv** [comment]
Hi @filbabic,

Thank you for the detailed explanation, and I apologize for the issue. We’ll work on fixing it as soon as possible and will let you know once it’s resolved.

Thanks!

**Comment by dgtv** [comment]
Hello Filip @filbabic,

Your problem has been addressed in https://github.com/talkable/android-sdk/pull/13. After QA stage it will be released and could be used. I'll notify you after the release.

Thanks!

**Comment by filbabic** [comment]
@dgtv Thank you so much!

Really appreciate the quick turnover, I'll keep an eye out on the releases and make sure to update accordingly on our end ^^

**Comment by dgtv** [comment]
Hi @filbabic,
New version [0.5.13](https://github.com/talkable/android-sdk/releases/tag/0.5.13) of Talkable Android SDK with the fix has been released.

**Comment by filbabic** [comment]
Thank you so much! I'll do my best to update our app this week with it.

**Comment by filbabic** [comment]
Just a note: updated the app and everything works fine, thank you for the quick turnover!

**Comment by dgtv** [comment]
@filbabic Awesome, thanks for the update!
Have you been able to review how the Talkable Android SDK is integrated into your application to ensure that `Talkable.showOffer` is called only when a Talkable Offer should be shown to users because currently it looks like it is called in more general cases which leads to not usual increase of traffic from Noom Android application?

**Comment by filbabic** [comment]
I have no idea who owns that and I've only encountered the Talkable SDK when I was looking to update Facebook, so I'll reach out to the team and see what they think!

**Comment by dgtv** [comment]
@filbabic Awesome, thanks for the details! By the way, we've been discussing the `Talkable.showOffer` placement thing with Andrei and Dan, in case that's helpful.
